name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push Wsgi Server
      uses: docker/build-push-action@v4
      with:
        context: .
        target: wsgi-server
        push: true
        tags: pzubuntu593/chatgpt-ui-wsgi-server:latest-gpt3,pzubuntu593/chatgpt-ui-wsgi-server:${{ github.ref_name }}-gpt3
    -
      name: Build and push Web Server
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: wongsaang/chatgpt-ui-web-server:latest-gpt3,wongsaang/chatgpt-ui-web-server:${{ github.ref_name }}-gpt3
